[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Dodeca Shaven <dodeca@tutamail.com>"]
repository = "https://github.com/dodeca1337/ddevmem"
license = "MIT"

[package]
name = "ddevmem"
keywords = ["devmem"]
description = "Library to access linux /dev/mem"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
memmap2 = "0.9.5"
page_size = "0.6.0"
bytemuck = "1.19.0"
concat-idents = "1.1.5"
