//! The conversion trait behind `as Type` bitfields.

/// A type a bitfield can be read as and written from: `field: 4..=5 as Type`.
///
/// Every enum declared inside [`register_map!`](crate::register_map)
/// implements it, which is what lets an enum generated by one map type a
/// field of another. Implement it by hand to give a bitfield a type of your
/// own — a newtype with a unit, an enum shared across crates, and so on.
///
/// Values cross the trait as the field's bits shifted down to bit 0 and
/// widened to `u64`.
///
/// ```rust,no_run
/// use ddevmem::{register_map, FieldValue};
///
/// /// A clock divider stored as its base-2 logarithm.
/// #[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// pub struct Divider(pub u32);
///
/// impl FieldValue for Divider {
///     const VARIANTS: &'static [(&'static str, u64)] =
///         &[("1", 0), ("2", 1), ("4", 2), ("8", 3)];
///
///     fn from_bits(bits: u64) -> Self {
///         Divider(1 << bits)
///     }
///
///     fn to_bits(self) -> u64 {
///         u64::from(self.0.trailing_zeros())
///     }
/// }
///
/// register_map! {
///     pub unsafe map Clock (u32) {
///         0x00 => rw cr: u32 {
///             div: 4..=5 as Divider
///         }
///     }
/// }
/// # fn use_it(clock: &mut Clock) {
/// clock.set_cr_div(Divider(4)); // writes 0b10 into bits 5:4
/// # }
/// ```
pub trait FieldValue: Sized {
    /// Named values, as `(name, bits)` pairs, that the web UI offers in a
    /// dropdown. Leave it empty for a free-form numeric input.
    const VARIANTS: &'static [(&'static str, u64)] = &[];

    /// Decodes the field's bits.
    ///
    /// `bits` always fits the field, but may be any value within it —
    /// including encodings the hardware reserves — so this must not panic.
    fn from_bits(bits: u64) -> Self;

    /// Encodes the value. Bits above the field's width are discarded by the
    /// setter.
    fn to_bits(self) -> u64;
}
